version: '3'

services:
  hackergame:
    build: .
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=conf.settings.zfun
    volumes:
      - .:/opt/hackergame/:ro
      - ./var/:/var/opt/hackergame/
    depends_on:
      - memcached
      - postgres
  memcached:
    image: memcached
    restart: unless-stopped
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=hackergame
      - POSTGRES_PASSWORD=supersecret
    volumes:
      - db_data:/var/lib/postgresql/data
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 11000:80
    volumes:
      - ./conf/nginx-sites/zfun:/etc/nginx/conf.d/default.conf:ro
      - ./var/:/var/opt/hackergame/:ro
    depends_on:
      - hackergame

volumes:
  db_data:
