# Generated by Django 4.2.7 on 2024-01-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(unique=True)),
                ('group', models.TextField()),
                ('nickname', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('sno', models.TextField(null=True)),
                ('tel', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('gender', models.TextField(null=True)),
                ('qq', models.TextField(null=True)),
                ('website', models.TextField(null=True)),
                ('school', models.TextField(null=True)),
                ('grade', models.TextField(null=True)),
                ('major', models.TextField(null=True)),
                ('campus', models.TextField(null=True)),
                ('aff', models.TextField(null=True)),
                ('token', models.TextField()),
                ('suspicious', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(null=True)),
                ('suspicious_ddl', models.DateTimeField(null=True)),
            ],
            options={
                'permissions': [('full', '管理个人信息'), ('view', '查看个人信息'), ('view_ljyz', '查看连江一中个人信息')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_user', models.IntegerField(null=True)),
                ('context_time', models.DateTimeField()),
                ('context_elevated', models.BooleanField()),
                ('user', models.IntegerField()),
                ('group', models.TextField()),
                ('nickname', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('sno', models.TextField(null=True)),
                ('tel', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('gender', models.TextField(null=True)),
                ('qq', models.TextField(null=True)),
                ('website', models.TextField(null=True)),
                ('school', models.TextField(null=True)),
                ('grade', models.TextField(null=True)),
                ('major', models.TextField(null=True)),
                ('campus', models.TextField(null=True)),
                ('aff', models.TextField(null=True)),
                ('token', models.TextField()),
                ('suspicious', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(null=True)),
                ('suspicious_ddl', models.DateTimeField(null=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
