# Generated by Django 4.2.7 on 2024-01-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('category', models.TextField()),
                ('enabled', models.BooleanField()),
                ('detail', models.TextField()),
                ('url_orig', models.TextField(null=True)),
                ('prompt', models.TextField(null=True)),
                ('index', models.IntegerField(db_index=True)),
                ('flags', models.TextField()),
                ('check_url_clicked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['index'],
                'permissions': [('full', '管理题目'), ('view', '查看题目')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(unique=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ExprFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expr', models.TextField(db_index=True)),
                ('user', models.IntegerField(db_index=True)),
                ('flag', models.TextField(db_index=True)),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('expr', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Expr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_index', models.IntegerField()),
                ('expr', models.TextField(db_index=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('challenge', 'flag_index')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeURLRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(db_index=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('challenge', 'user')},
            },
        ),
    ]
