# Generated by Django 4.2.7 on 2024-01-06 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.TextField()),
                ('identity', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.TextField()),
                ('identity', models.TextField()),
                ('code', models.TextField(db_index=True)),
                ('expiration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='会被放入 <code>div</code> 的 HTML')),
                ('js', models.TextField(blank=True, help_text='会被放入 <code>script</code> 的 JS')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Hackergame')),
                ('description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True, default='Hackergame,CTF')),
                ('content', models.TextField(blank=True, default='<h1>Hackergame</h1>', help_text='会被放入 <code>div</code> 的 HTML')),
                ('js', models.TextField(blank=True, help_text='会被放入 <code>script</code> 的 JS')),
            ],
        ),
        migrations.CreateModel(
            name='Qa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='<h1>问与答</h1>', help_text='会被放入 <code>div</code> 的 HTML')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialProfileUsedRecord',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('content_type', models.CharField(default='学号', max_length=32)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.account')),
            ],
        ),
        migrations.AddConstraint(
            model_name='accountlog',
            constraint=models.UniqueConstraint(fields=('account', 'content_type'), name='unique_account_log_for_each_type'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('provider', 'identity')},
        ),
    ]
