# Generated by Django 4.2.7 on 2024-01-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('can_view_challenges', models.BooleanField()),
                ('can_try', models.BooleanField()),
                ('can_submit', models.BooleanField()),
                ('can_update_profile', models.BooleanField()),
                ('note', models.TextField(null=True)),
            ],
            options={
                'permissions': [('full', '管理定时器')],
                'default_permissions': (),
            },
        ),
    ]
