# Generated by Django 4.2.7 on 2024-01-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('enabled', models.BooleanField()),
            ],
            options={
                'permissions': [('full', '管理用户条款')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(db_index=True)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terms.terms')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
