# Generated by Django 4.2.7 on 2024-01-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(db_index=True)),
                ('group', models.TextField(db_index=True)),
                ('challenge', models.IntegerField(db_index=True)),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'permissions': [('full', '管理提交记录'), ('view', '查看提交记录')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(db_index=True)),
                ('group', models.TextField()),
                ('category', models.TextField(db_index=True)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='FlagViolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_user', models.IntegerField()),
                ('reason', models.TextField(null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.submission')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FlagFirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.IntegerField()),
                ('flag', models.IntegerField()),
                ('group', models.TextField(db_index=True)),
                ('user', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('challenge', 'flag', 'group')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeFirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.IntegerField()),
                ('group', models.TextField(db_index=True)),
                ('user', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('challenge', 'group')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeClear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(db_index=True)),
                ('group', models.TextField(db_index=True)),
                ('challenge', models.IntegerField(db_index=True)),
                ('time', models.DateTimeField(db_index=True)),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('user', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='FlagClear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(db_index=True)),
                ('group', models.TextField(db_index=True)),
                ('challenge', models.IntegerField(db_index=True)),
                ('flag', models.IntegerField()),
                ('time', models.DateTimeField(db_index=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.submission')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('user', 'challenge', 'flag')},
            },
        ),
    ]
